#!/usr/bin/env python3
"""
Scan papers/notes/*.md → produce:
- papers/index.json  (machine-readable, Claude reads this)
- papers/INDEX.md    (human-readable table)
"""
from __future__ import annotations
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTES = ROOT / "notes"
LIBRARY = ROOT / "library"


def parse_frontmatter(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    out = {}
    for line in m.group(1).split("\n"):
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k = k.strip()
        v = v.strip()
        if v == "null":
            out[k] = None
        elif v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            out[k] = [x.strip().strip('"') for x in inner.split(",") if x.strip()] if inner else []
        else:
            try:
                if "." not in v and v.lstrip("-").isdigit():
                    out[k] = int(v)
                else:
                    out[k] = v.strip('"')
            except ValueError:
                out[k] = v.strip('"')
    return out


def main():
    records = []
    for note in sorted(NOTES.glob("*.md")):
        fm = parse_frontmatter(note.read_text())
        if not fm.get("id"):
            continue
        fm["note"] = f"notes/{note.name}"
        records.append(fm)

    # Sort by relevance then year desc
    relevance_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    records.sort(key=lambda r: (relevance_order.get(r.get("relevance"), 9), -(r.get("year") or 0)))

    # index.json
    (ROOT / "index.json").write_text(json.dumps(records, indent=2, ensure_ascii=False))

    # INDEX.md
    icon = {
        "downloaded": "✅",
        "vpn-required": "🔒",
        "failed": "❓",
        "pending": "⏳",
    }
    lines = [
        "# Papers — INDEX",
        "",
        "Auto-generated by `scripts/build_index.py`. **Source of truth = `notes/*.md` frontmatter.**",
        "",
        "Status: ✅ downloaded · 🔒 closed (VPN PoliMi) · ❓ failed (link ambiguo) · ⏳ pending",
        "",
        "Relevance: **critical** = anchor della tesi · **high** = direct comparator/competitor · **medium** = contesto · **low** = nice-to-have",
        "",
        f"**Total: {len(records)} paper · {sum(1 for r in records if r.get('status') == 'downloaded')} downloaded · "
        f"{sum(1 for r in records if r.get('status') == 'vpn-required')} VPN · "
        f"{sum(1 for r in records if r.get('status') in ('failed', 'pending'))} aperti**",
        "",
        "| | ID | Year | Title | Venue | Rel. | Tags |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in records:
        title = (r.get("title") or "")[:75]
        tags = ", ".join((r.get("tags") or [])[:4])
        venue = (r.get("venue") or "")[:20]
        lines.append(
            f"| {icon.get(r.get('status'), '?')} "
            f"| [`{r['id']}`]({r['note']}) "
            f"| {r.get('year') or '—'} "
            f"| {title} "
            f"| {venue} "
            f"| {r.get('relevance', '—')} "
            f"| {tags} |"
        )

    # Tag groups
    lines.extend(["", "## By topic", ""])
    tag_map: dict[str, list[str]] = {}
    for r in records:
        for t in (r.get("tags") or []):
            tag_map.setdefault(t, []).append(r["id"])
    for t in sorted(tag_map):
        lines.append(f"- **{t}** ({len(tag_map[t])}): " + ", ".join(f"`{x}`" for x in tag_map[t]))

    # Slide-mapping
    lines.extend(["", "## By slide section", ""])
    slide_map: dict[str, list[str]] = {}
    for r in records:
        for s in (r.get("in_slides") or []):
            slide_map.setdefault(s, []).append(r["id"])
    if slide_map:
        for s in sorted(slide_map):
            lines.append(f"- **{s}** ({len(slide_map[s])}): " + ", ".join(f"`{x}`" for x in slide_map[s]))
    else:
        lines.append("_(no slide assignments yet — fill `in_slides:` in note frontmatter)_")

    (ROOT / "INDEX.md").write_text("\n".join(lines) + "\n")
    print(f"Wrote INDEX.md and index.json — {len(records)} records")


if __name__ == "__main__":
    main()
