"""DataModule for the synthetic 13-band multispectral dataset.

Wraps the GeoTIFF patches generated by scripts/generate_synthetic_ms.py
for pipeline validation before real Sentinel-2 data arrives.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import numpy as np
import pytorch_lightning as pl
import rasterio
import torch
from torch.utils.data import DataLoader, Dataset, random_split

logger = logging.getLogger(__name__)


class SyntheticMSDataset(Dataset):
    """Dataset for synthetic multispectral GeoTIFF patches.

    Args:
        root: Directory containing {id}_bands.tif and {id}_label.json.
        band_indices: Subset of 13 bands to load (None = all 13).
        img_size: Resize patches to this size (via center crop or padding).
            If None, return raw 64×64.
        transform: Optional transform applied to the image tensor.
    """

    def __init__(
        self,
        root: str | Path,
        band_indices: list[int] | None = None,
        img_size: int | None = 224,
        transform: Any = None,
    ) -> None:
        self.root = Path(root)
        self.band_indices = band_indices
        self.img_size = img_size
        self.transform = transform

        # Discover patches
        tif_files = sorted(self.root.glob("*_bands.tif"))
        self.ids = [f.stem.replace("_bands", "") for f in tif_files]
        if not self.ids:
            raise FileNotFoundError(f"No *_bands.tif files found in {root}")

        logger.info(
            "SyntheticMSDataset: %d patches, %s bands, img_size=%s",
            len(self.ids),
            len(band_indices) if band_indices else 13,
            img_size,
        )

    def __len__(self) -> int:
        return len(self.ids)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        patch_id = self.ids[idx]

        # Load GeoTIFF
        tif_path = self.root / f"{patch_id}_bands.tif"
        with rasterio.open(tif_path) as src:
            data = src.read().astype(np.float32)  # (13, H, W)

        # Band selection
        if self.band_indices is not None:
            data = data[self.band_indices]

        image = torch.from_numpy(data)

        # Resize to img_size via interpolation if needed
        if self.img_size is not None and (image.shape[1] != self.img_size or image.shape[2] != self.img_size):
            image = torch.nn.functional.interpolate(
                image.unsqueeze(0),
                size=(self.img_size, self.img_size),
                mode="bilinear",
                align_corners=False,
            ).squeeze(0)

        if self.transform is not None:
            image = self.transform(image)

        # Load label
        label_path = self.root / f"{patch_id}_label.json"
        with open(label_path) as f:
            label_data = json.load(f)

        return {
            "image": image,
            "label": torch.tensor(label_data["binary"], dtype=torch.float32),
            "category_id": label_data.get("category_id", 0),
            "filename": patch_id,
        }


class SyntheticMSDataModule(pl.LightningDataModule):
    """Lightning DataModule for synthetic MS patches.

    Args:
        root: Path to data/synthetic_ms/.
        band_indices: Subset of bands (None = all 13).
        img_size: Target image size (default 224 for ViT).
        batch_size: Batch size.
        val_frac: Fraction of data for validation.
        num_workers: DataLoader workers.
        seed: Random split seed.
    """

    def __init__(
        self,
        root: str | Path = "data/synthetic_ms",
        band_indices: list[int] | None = None,
        img_size: int = 224,
        batch_size: int = 32,
        val_frac: float = 0.2,
        num_workers: int = 4,
        seed: int = 42,
    ) -> None:
        super().__init__()
        self.save_hyperparameters()
        self.root = Path(root)
        self.band_indices = band_indices
        self.img_size = img_size
        self.batch_size = batch_size
        self.val_frac = val_frac
        self.num_workers = num_workers
        self.seed = seed

        self.train_ds: Dataset | None = None
        self.val_ds: Dataset | None = None

    def setup(self, stage: str | None = None) -> None:
        full_ds = SyntheticMSDataset(
            root=self.root,
            band_indices=self.band_indices,
            img_size=self.img_size,
        )

        n_val = int(len(full_ds) * self.val_frac)
        n_train = len(full_ds) - n_val
        self.train_ds, self.val_ds = random_split(
            full_ds, [n_train, n_val],
            generator=torch.Generator().manual_seed(self.seed),
        )
        logger.info("Split: %d train, %d val", n_train, n_val)

    def train_dataloader(self) -> DataLoader:
        return DataLoader(
            self.train_ds,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            pin_memory=True,
        )

    def val_dataloader(self) -> DataLoader:
        return DataLoader(
            self.val_ds,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=True,
        )

    # Test uses val split for smoke tests
    def test_dataloader(self) -> DataLoader:
        return self.val_dataloader()
